#
# Build environment
#

# The Qt SDK path
SET(QT_SDK_DIR "D:/Qt/5.15.2/msvc2019")


# The libvlc SDK path
SET(LIBVLC_VERSION      0x030021)
SET(LIBVLC_LIBRARY      "${CMAKE_SOURCE_DIR}/vlc-3.0.21/win32/lib/libvlc.lib")
SET(LIBVLCCORE_LIBRARY  "${CMAKE_SOURCE_DIR}/vlc-3.0.21/win32/lib/libvlccore.lib")
SET(LIBVLC_INCLUDE_DIR  "${CMAKE_SOURCE_DIR}/vlc-3.0.21/win32/include")
SET(LIBVLC_BIN_DIR      "${CMAKE_SOURCE_DIR}/vlc-3.0.21/win32/bin")

SET(LIBVLC_PLUGINS_DIR  "${LIBVLC_BIN_DIR}/plugins")
SET(LIBVLC_LIB_DIR      "${LIBVLC_BIN_DIR}/lib")

# VLCQt Version
SET(PROJECT_VERSION_MAJOR 2)
SET(PROJECT_VERSION_MINOR 0)
SET(PROJECT_VERSION_PATCH 1)


SET(VLCQt_OUT_DIR "${CMAKE_SOURCE_DIR}/out")